/*
 * Copyright (C) 2014 Philippe Tjon - A - Hen, philippe@tjonahen.nl
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package nl.tjonahen.abk.backend;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * Other jsonProviders are.
 * 
 * Class jsonProvider = Class.forName("org.glassfish.jersey.moxy.json.MoxyJsonFeature"); 
 * Class jsonProvider = Class.forName("org.glassfish.jersey.jettison.JettisonFeature");
 * 
 * @author Philippe Tjon - A - Hen, philippe@tjonahen.nl
 */
@ApplicationPath(ResourcePaths.APPLICATION_PATH)
public class AbkApplication extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        // following code can be used to customize Jersey 2.0 JSON provider:
        try {
            Class jsonProvider;
            jsonProvider = Class.forName("org.glassfish.jersey.jackson.JacksonFeature");
            resources.add(jsonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method. It is automatically re-generated by NetBeans REST support to
     * populate given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(nl.tjonahen.abk.backend.AbkCrossOriginResourceSharingFilter.class);
        resources.add(nl.tjonahen.abk.backend.boundry.account.AccountsResource.class);
        resources.add(nl.tjonahen.abk.backend.boundry.contraaccount.ContraAccountsResource.class);
        resources.add(nl.tjonahen.abk.backend.boundry.costcenter.CostCentersResource.class);
        resources.add(nl.tjonahen.abk.backend.boundry.transaction.FinancialTransactionsResource.class);
    }
}
