# Abk Client application (frontend)
# docker build -t tjonahen/abk-client  .
# VERSION 1.0.0
FROM tjonahen/http-server
MAINTAINER Philippe Tjon-A-Hen <philippe.tjonahen.nl>
COPY dist content
WORKDIR content
